name: ◡🥀𝓐𝓸𝓲𝓒𝓱𝓪𝓷🥀◡ ωєв

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: 📥 Check Source
        uses: actions/checkout@v5
        
      - name: 📒 Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
      
      - run: npm install
      - run: npm run build
      
      - name: Đăng tải ➺【Artifact】
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Triển khai ➺【GitHub Pages】
        id: deployment
        uses: actions/deploy-pages@v5
        
      - name: Delete deployment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.AOI_ACTIONS }}
          environment: github-pages
          onlyRemoveDeployments: true
        
      - name: 🗑️ 𝐎𝐋𝐃 𝐖𝐎𝐑𝐊𝐅𝐋𝐎𝐖𝐒
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate \
            --jq '.workflow_runs | sort_by(.created_at) | reverse | .[5:] | map(select(.status=="completed")) | .[].id' \
            | while read run; do
                echo "🗑️ đã xóa $run"
                gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_ACTIONS }}

      - name: 🗑️ 𝐎𝐋𝐃 𝐂𝐀𝐂𝐇𝐄
        run: |
          gh cache list --json id,createdAt \
            | jq 'sort_by(.createdAt) | reverse | .[5:] | .[].id' \
            | while read id; do
                echo "🗑️ đã xóa $id"
                gh cache delete "$id"
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_ACTIONS }}
