name: Deploy Aoi Website

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build site
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5

      - name: ♻️𝐎𝐋𝐃 𝐖𝐎𝐑𝐊𝐅𝐋𝐎𝐖𝐒
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate \
            --jq '.workflow_runs | sort_by(.created_at) | reverse | .[5:] | map(select(.status=="completed")) | .[].id' \
            | while read run; do
                echo "🗑️ đã xóa $run"
                gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ♻️𝐎𝐋𝐃 𝐂𝐀𝐂𝐇𝐄
        run: |
          gh cache list --json id,createdAt \
            | jq 'sort_by(.createdAt) | reverse | .[5:] | .[].id' \
            | while read id; do
                echo "🗑️ đã xóa $id"
                gh cache delete "$id"
              done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
