name: ◡🥀𝓐𝓸𝓲𝓒𝓱𝓪𝓷🥀◡ ωєв

on:
  push:
    branches: ["main"]
 # workflow_dispatch:

permissions:
  actions: write
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: ⚡ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: 📦 Install deps
        run: pnpm install --frozen-lockfile

      - name: 🏗 Build
        run: pnpm build
        
      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Triển khai ➺【GitHub Pages】
        id: deployment
        uses: actions/deploy-pages@v5
        
      - name: 🗑️ 𝐎𝐋𝐃 deployment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.AOI_ACTIONS }}
          environment: github-pages
          onlyRemoveDeployments: true
        
      - name: 🗑️ 𝐎𝐋𝐃 𝐖𝐎𝐑𝐊𝐅𝐋𝐎𝐖𝐒
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate \
            --jq '.workflow_runs | sort_by(.created_at) | reverse | .[5:] | map(select(.status=="completed")) | .[].id' \
            | while read run; do
                echo "🗑️ đã xóa $run"
                gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_ACTIONS }}

      - name: 🗑️ 𝐎𝐋𝐃 𝐂𝐀𝐂𝐇𝐄
        run: |
          gh cache list --json id,createdAt \
            | jq 'sort_by(.createdAt) | reverse | .[5:] | .[].id' \
            | while read id; do
                echo "🗑️ đã xóa $id"
                gh cache delete "$id"
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_ACTIONS }}
